//   // import { Geist, Geist_Mono } from "next/font/google";
//   // import "./globals.css";

//   // const geistSans = Geist({
//   //   variable: "--font-geist-sans",
//   //   subsets: ["latin"],
//   // });

//   // const geistMono = Geist_Mono({
//   //   variable: "--font-geist-mono",
//   //   subsets: ["latin"],
//   // });

//   // export const metadata = {
//   //   title: "Create Next App",
//   //   description: "Generated by create next app",
//   // };

//   // export default function RootLayout({ children }) {
//   //   return (
//   //     <html lang="en">
//   //       <body
//   //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//   //       >
//   //         {children}
//   //       </body>
//   //     </html>
//   //   );
//   // }

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/NavBar";
// import Footer from "./components/Footer";
// import WhatsAppFloat from "./components/WhatsAppFloat";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Esthetix Dental | Dentist in Ranchi",
//   description:
//     "Esthetix Dental provides comprehensive dental care in Ranchi including implants, cosmetic dentistry, preventive care, and smile enhancement.",
// };

// export default function RootLayout({ children }) {

//   const dentistSchema = {
//     "@context": "https://schema.org",
//     "@type": "Dentist",
//     "name": "Esthetix Dental",
//     "image": "https://yourdomain.com/images/clinic.jpg",
//     "url": "https://yourdomain.com",
//     "telephone": "+91XXXXXXXXXX",
//     "priceRange": "₹₹",
//     "address": {
//       "@type": "PostalAddress",
//       "streetAddress": "107, 1st Floor, Modi Heights, Opposite All India Radio",
//       "addressLocality": "Ranchi",
//       "addressRegion": "Jharkhand",
//       "postalCode": "834001",
//       "addressCountry": "IN"
//     },
//     "geo": {
//       "@type": "GeoCoordinates",
//       "latitude": "23.3789062",
//       "longitude": "85.3135388"
//     },
//     "openingHours": [
//       "Mo-Sa 10:00-19:00",
//       "Su 10:00-13:00"
//     ],
//     "sameAs": [
//       "https://www.google.com/maps/place/Esthetix+Dental"
//     ]
//   };

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />
//         <WhatsAppFloat />
//         <script
//           type="application/ld+json"
//           dangerouslySetInnerHTML={{ __html: JSON.stringify(dentistSchema) }}
//         />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import Footer from "./components/Footer";
import WhatsAppFloat from "./components/WhatsAppFloat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Best Dental Clinic in Ranchi | Esthetix Dental",
  description:
    "Esthetix Dental is a trusted dental clinic in Ranchi offering implants, root canal, cosmetic dentistry, and smile design with 10+ years experience.",
  keywords: [
    "dentist in Ranchi",
    "best dental clinic Ranchi",
    "root canal Ranchi",
    "dental implants Ranchi",
    "cosmetic dentist Ranchi",
  ],
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "Esthetix Dental - Best Dental Clinic in Ranchi",
    description:
      "Trusted dental clinic in Ranchi with 10+ years experience in advanced and cosmetic dentistry.",
    url: "https://esthetixdentalcare.in",
    siteName: "Esthetix Dental",
    images: [
      {
        url: "https://esthetixdentalcare.in/images/clinic.webp",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Esthetix Dental - Ranchi",
    description: "Advanced dental care in Ranchi",
    images: ["https://esthetixdentalcare.in/images/clinic.webp"],
  },
};

export default function RootLayout({ children }) {
  const dentistSchema = {
    "@context": "https://schema.org",
    "@type": "Dentist",
    name: "Esthetix Dental",
    image: "https://esthetixdentalcare.in/images/clinic.webp",
    url: "https://esthetixdentalcare.in",
    telephone: "+917677279977", // ⚠️ replace with real number
    priceRange: "₹₹",
    address: {
      "@type": "PostalAddress",
      streetAddress:
        "107, 1st Floor, Modi Heights, Opposite All India Radio",
      addressLocality: "Ranchi",
      addressRegion: "Jharkhand",
      postalCode: "834001",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "23.3789062",
      longitude: "85.3135388",
    },
    openingHours: ["Mo-Sa 10:00-19:00", "Su 10:00-13:00"],
    sameAs: [
      "https://www.google.com/maps/place/Esthetix+Dental",
    ],
  };

  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(dentistSchema),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <WhatsAppFloat />
        {children}
        <Footer />
      </body>
    </html>
  );
}